image: python:3.9-slim

stages:
  - deploy

pages:
  stage: deploy
  script:
    - apt-get update
    - apt-get install -y build-essential
    - pip install -r requirements.txt
    - pip install uvicorn gunicorn
    - pip install fastapi
    - pip freeze > requirements.txt
  artifacts:
    paths:
      - public/
  only:
    - main

deploy_to_pages:
  stage: deploy
  script:
    - mkdir -p public
    - cp main.py public/
    - cp requirements.txt public/
    - cp -r temp_files public/ || mkdir -p public/temp_files
  artifacts:
    paths:
      - public/
  only:
    - main